name: gh-pages-external

on:
  push:
    branches: [ main, gh-pages-external ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.10.0
        with:
          cache: true

      - name: Cache packages
        uses: actions/cache@v3.3.1
        with:
          path: ${{ env.PUB_CACHE }}
          key: deps-${{ hashFiles('**/pubspec.lock') }}

      - name: Restore packages
        run: flutter pub get

      - name: Creates web build
        run: flutter build web --release

      - name: Replace base href
        run: sed -i 's\<base href="/">\<base href="./">\g' build/web/index.html

      - name: Commit and push
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          JIT_OWNER: ${{ secrets.JIT_OWNER }}
          JIT_REPO: ${{ secrets.JIT_REPO }}
        run: |
          git clone https://$API_TOKEN_GITHUB@github.com/$JIT_OWNER/$JIT_REPO.git
          cd $JIT_REPO
          rm -rf *
          mv build/web/ .
          git commit -am update || echo "no changes"
          git push

      - uses: lhotari/action-upterm@v1