name: gh-pages-external

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.10.0
        with:
          cache: true

      - name: Cache packages
        uses: actions/cache@v3.3.1
        with:
          path: ${{ env.PUB_CACHE }}
          key: deps-${{ hashFiles('**/pubspec.lock') }}

      - name: Restore packages
        run: flutter pub get

      - name: creates web build
        run: flutter build web --release

      - name: replace base href
        run: sed -i 's\<base href="/">\<base href="./">\g' build/web/index.html

      - name: Pushes to chdata-pages repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build/web'
          env:
            CPINA_OWNER: ${{ github.event.repository.owner }}
            CPINA_REPO: '${{ github.event.repository.name }}-pages'
          destination-github-username: $CPINA_OWNER
          destination-repository-name: $CPINA_REPO
          user-email: update
          target-branch: main
